### ISSUE TITLE
Histogram representation of data color space

### ISSUE THREAD

**Issue by HugoB** [LaboratoryOpticsBiosciences/napari-brainbow-diagnose#10]
## Pitch

The user should be able to visualize the image trough the channel space that in 3 channel brainbow can be seen as a rgb color cube Each pixel is a ratio of the different channel. Creating an histogram of the distribution of pixel in this color cube could help visualize the data down the line.

To start, we would like to see the color space in a 3D cube with each axis corresponding to one channel.
![image](https://user-images.githubusercontent.com/94049435/203516504-d19ac142-32c0-4fc5-8276-f32c2cf07aa8.png)

Each pixel `p` with the channel `(r, g, b)` in this color space is one point localized in `(p_r, p_g, r_b)`.
The color space axis range should match either:
- [min max] of the whole brainbow image

Binning is to be decided (10,10,10)  could be a start.
 
## Additional context
Check quickly how the brainbow fluorescence is distributed. We aim to have clean clustered cone.

## branch
`color_histogram`

**Comment by ClementCaporal** [comment]
You can now draw complex shape in HS space

**Comment by ClementCaporal** [comment]
You can now draw complex selection shape in 2D HS disk
